[package]
name = "cbeta-parse"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "CBETA TEI P5 parser"

[dependencies]
cbeta-core.workspace = true
thiserror.workspace = true
quick-xml.workspace = true
unicode-normalization.workspace = true
ferrous-opencc.workspace = true

[lints]
workspace = true
